name: space_flight_news
description: Space Flight News
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.2.0
  flutter: ^3.16.0

dependencies:
  auto_route: 7.8.4
  barrel_files_annotation: 0.1.1
  dio: 5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.4.1
  get_it: 7.6.7
  i69n: 2.1.0
  injectable: 2.3.2
  intl: 0.18.1
  json_annotation: 4.8.1
  retrofit: 4.0.3
  url_launcher: 6.2.4

dev_dependencies:
  auto_route_generator: 7.3.2
  barrel_files: 0.1.1
  bdd_widget_test: 1.6.4
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0
  injectable_generator: 2.4.1
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.4.6
  json_serializable: 6.7.1
  retrofit_generator: 8.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/presentation/assets
  assets:
    outputs:
      package_parameter_enabled: true

dependency_overrides:
  file: 6.1.4
